### ISSUE TITLE
Unwanted push in the main branch

### ISSUE THREAD

**Issue by RoberPlaza** [kpanicc/IS0II#5]
Hi, by accident I pushed the new version instead of commiting it.
Please remove the SCTSpotif-placeOrder directory ASAP.
Command: git rm -r SCTSpotif-placeOrder

Thank you and sorry for the inconvenience

**Comment by Juanjoglvz** [comment]
The boss will make the rollback and then I will inspect the fullfulment of the requirements in your own branch.
I close the issue now.
